version: "3"

services:
  rabbitmq:
    hostname: sample-rabbit
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 8080:15672
      - 5672:5672
    volumes:
      - "./volume:/var/lib/rabbitmq"
